### ISSUE TITLE
No access control?

### ISSUE THREAD

**Issue by mariusk** [NotSqrt/mattermost-integration-gitlab#15]
I've gotten everything working, BUT it means I'm now running a daemon on port 5000 (or any other port number) that anybody can connect to (and create messages in my Mattermost channel). I could use firewall rules to limit connections, but then I would need to know all IPs Gitlab could use. Another alternative would be to add some magic cookie or similar to at least minimize unauthorized connections to the port. Is any of this supported already, and if so, how would I do it?

**Comment by NotSqrt** [comment]
Hello,

There's no access control within this app.
I only use it on localhost, so no exposed service or open port..

To handle authentication, I guess I would set up a reverse proxy (nginx/apache) with basic auth in front of this daemon, and potentially HTTPS.
I assume that using a hook url of the form http://username:password@ip:port in gitlab will work, so that basic auth can be used easily ...

That's about it without modifications of the python code.

**Comment by mariusk** [comment]
Ah, yes, if you self host there are no issues. If you use hosted Gitlab however.. Thanks for responding anyway.
