### ISSUE TITLE
Unable to retrieve address for web hooks

### ISSUE THREAD

**Issue by Magicie** [NotSqrt/mattermost-integration-gitlab#18]
Is the installation guide up-to-date, please? I am unable to retrieve address for web hooks.

> Set up your Mattermost instance to receive incoming webhooks
> 
> Log in to your Mattermost account. Click the three dot menu at the top of the left-hand side and go to Account Settings > Integrations > Incoming Webhooks.
> Under Add a new incoming webhook select the channel in which you want GitLab notifications to appear, then click Add to create a new entry.
> Copy the contents next to URL of the new webhook you just created (we'll refer to this as https://&lt;your-mattermost-webhook-URL&gt;).

Thanks in advance for any help.

**Comment by NotSqrt** [comment]
Hi,

With mattermost v3.4.0, the steps seem to be:
1. Log in to your Mattermost account. 
2. Click the three dot menu at the top of the left-hand side **and go to Integrations > Incoming Webhooks**
3. Under `Add a new incoming webhook`, select the channel in which you want GitLab notifications to appear, then click Add to create a new entry.
4. Copy the contents next to URL of the new webhook you just created (we'll refer to this as https://<your-mattermost-webhook-URL>).

So, it's just a full menu now instead of being included in Account settings.

Is that what you needed ?

**Comment by NotSqrt** [comment]
These steps just have been updated.
